/*
 * This source file was generated by the Gradle 'init' task
 */
package index

import org.dopc.clientserverconfig.configclientserver.ClientServer


fun main() {
    val clientServer: ClientServer = ClientServer()
    clientServer.deliveryOrderFeeCalculator()
}
