/*
 * This source file was generated by the Gradle 'init' task
 */
package index

import clientserverconfig.ClientServer

fun main() {
    val clientServer = ClientServer()
    clientServer.deliveryOrderFeeCalculator()
}
